services:
  joshdoesdev:
    container_name: joshdoesdev
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .git
        - action: rebuild
          path: package.json
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    networks:
      - app-net

volumes:
  db-data:
networks:
  app-net:
    driver: bridge
